#include "test_framework.h"
#include "log/log.h"

#include <string.h>
#include <stdio.h>

void test_log_redact(TestCounters *tc) {
    char out[128];

    /* A realistic-shaped token: "rmm_" + 64 hex chars, as generated by
     * RomM's backend ("rmm_" + secrets.token_hex(32)) — see
     * docs/architecture.md §3. */
    char middle[57];
    memset(middle, '0', sizeof(middle) - 1);
    middle[sizeof(middle) - 1] = '\0';
    char token[4 + 4 + 56 + 4 + 1];
    snprintf(token, sizeof(token), "rmm_ab12%sff90", middle);

    log_redact_bearer_token(token, out, sizeof(out));
    TEST_CHECK(tc, strcmp(out, "rmm_ab12...ff90 (68 chars)") == 0);
    /* The redacted form must never contain the token's actual middle
     * section verbatim. */
    TEST_CHECK(tc, strstr(out, middle) == NULL);

    /* Non-rmm_ tokens are never echoed back */
    log_redact_bearer_token("some-other-secret-value", out, sizeof(out));
    TEST_CHECK(tc, strcmp(out, "(no token)") == 0);

    log_redact_bearer_token(NULL, out, sizeof(out));
    TEST_CHECK(tc, strcmp(out, "(no token)") == 0);

    /* A short opaque part (shorter than the head+tail preview) is redacted
     * to a fixed marker rather than leaking it piecemeal. */
    log_redact_bearer_token("rmm_ab", out, sizeof(out));
    TEST_CHECK(tc, strcmp(out, "rmm_***") == 0);
    TEST_CHECK(tc, strstr(out, "ab") == NULL);

    /* Full Authorization header value */
    char header[16 + sizeof(token)];
    snprintf(header, sizeof(header), "Bearer %s", token);
    log_redact_auth_header(header, out, sizeof(out));
    TEST_CHECK(tc, strcmp(out, "Bearer rmm_ab12...ff90 (68 chars)") == 0);

    log_redact_auth_header("Bearer some-oauth-jwt-value", out, sizeof(out));
    TEST_CHECK(tc, strcmp(out, "Bearer ***") == 0);
    TEST_CHECK(tc, strstr(out, "oauth-jwt") == NULL);

    log_redact_auth_header("Basic dXNlcjpwYXNz", out, sizeof(out));
    TEST_CHECK(tc, strcmp(out, "***") == 0);

    log_redact_auth_header(NULL, out, sizeof(out));
    TEST_CHECK(tc, strcmp(out, "(no auth header)") == 0);
}
