#include "mockdata/mock_library.h"

/* Fictional placeholder entries only — never real game titles or metadata.
 * Used to exercise the UI and pagination logic before a real RomM server
 * is connected. Designated initializers on purpose: RommGame has grown
 * fields more than once, and positional initializers silently
 * misassign values when that happens. */
const RommGame MOCK_PS5_GAMES[] = {
    {.id = 1,
     .title = "Sample Adventure",
     .fs_name = "Sample Adventure",
     .title_id = "CUSA00001",
     .version = "1.02",
     .format = ROMM_FORMAT_FOLDER,
     .fs_size_bytes = 42ULL * 1024 * 1024 * 1024,
     .has_cover_art = true},
    {.id = 2,
     .title = "Demo Racer",
     .fs_name = "Demo Racer",
     .title_id = "CUSA00002",
     .version = "1.00",
     .format = ROMM_FORMAT_FOLDER,
     .fs_size_bytes = 58ULL * 1024 * 1024 * 1024,
     .has_cover_art = true},
    {.id = 3,
     .title = "Placeholder Quest",
     .fs_name = "Placeholder Quest.ffpkg",
     .title_id = "CUSA00003",
     .version = "",
     .format = ROMM_FORMAT_FFPKG,
     .fs_size_bytes = 71ULL * 1024 * 1024 * 1024,
     .has_cover_art = false},
    {.id = 4,
     .title = "Test Arena Online",
     .fs_name = "Test Arena Online",
     .title_id = "CUSA00004",
     .version = "1.15",
     .format = ROMM_FORMAT_FOLDER,
     .fs_size_bytes = 35ULL * 1024 * 1024 * 1024,
     .has_cover_art = true},
    {.id = 5,
     .title = "Example Puzzle Co-op",
     .fs_name = "Example Puzzle Co-op.exfat",
     .title_id = "CUSA00005",
     .version = "1.03",
     .format = ROMM_FORMAT_EXFAT,
     .fs_size_bytes = 18ULL * 1024 * 1024 * 1024,
     .has_cover_art = true},
    {.id = 6,
     .title = "Fixture Platformer Deluxe",
     .fs_name = "Fixture Platformer Deluxe",
     .title_id = "",
     .version = "",
     .format = ROMM_FORMAT_FOLDER,
     .fs_size_bytes = 26ULL * 1024 * 1024 * 1024,
     .has_cover_art = false},
    {.id = 7,
     .title = "Mockup Battle Royale",
     .fs_name = "Mockup Battle Royale",
     .title_id = "CUSA00007",
     .version = "2.01",
     .format = ROMM_FORMAT_FOLDER,
     .fs_size_bytes = 93ULL * 1024 * 1024 * 1024,
     .has_cover_art = true},
    {.id = 8,
     .title = "Sandbox City Builder",
     .fs_name = "Sandbox City Builder.ffpfs",
     .title_id = "CUSA00008",
     .version = "1.40",
     .format = ROMM_FORMAT_FFPFS,
     .fs_size_bytes = 64ULL * 1024 * 1024 * 1024,
     .has_cover_art = true},
};

const size_t MOCK_PS5_GAMES_COUNT =
    sizeof(MOCK_PS5_GAMES) / sizeof(MOCK_PS5_GAMES[0]);
